runtime: python37
service: default
entrypoint: gunicorn -b :$PORT main:app
default_expiration: "7d"
instance_class: F2
automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
  target_cpu_utilization: 0.85
  target_throughput_utilization: 0.8
  max_concurrent_requests: 20
handlers:
  - url: .*
    secure: always
    script: auto
env_variables:
  PROD: True
